---
mqtt:
  broker: localhost
  username: mqtt
  password: mqtt1234
  node_id: mqtt_mesh
mesh:
  <hass_device_id>:
    uuid: <bluetooth_mesh_device_uuid>
    name: <hass_device_name>
    type: light # Only type supported for now.
    relay: false # Whether this node should act as a Bluetooth Relay
