# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BLEmesh2mqtt dev add-on
version: dev
slug: blemesh2mqtt
description: Example blemesh2mqtt add-on dev, full access,v1
url: "https://github.com/nitrokart/BLEmesh2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_dbus: true
host_network: true
apparmor: false
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - SYS_RESOURCE
  - SYS_PTRACE
  - SYS_MODULE
  - DAC_READ_SEARCH
map:
  - share:rw
full_access: true
options:
  message: "Hello world..."
schema:
  message: "str?"
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
